/* $Id: eps2c,v 1.3 2008/11/29 20:42:45 dan Exp $ */

/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with eps2c            ******** */

#include <stdio.h>


void air_coil_eps(FILE *fp)
{
fprintf(fp,"%% We are currently where the top center of the figure should be.\n");
fprintf(fp,"%% First figure out where the text will be when we continue\n");
fprintf(fp,"%% after the figure\n");
fprintf(fp,"%%\n");
fprintf(fp,"currentpoint 708 609 sub sub\n");
fprintf(fp,"gsave\n");
fprintf(fp,"currentpoint pop 141 329 add 2 div sub\n");
fprintf(fp,"currentpoint exch pop 708 sub \n");
fprintf(fp,"translate\n");
fprintf(fp,"%%\n");
fprintf(fp,"%%include the EPS file\n");
fprintf(fp,"%%\n");
fprintf(fp,"BEGINEPSFILE\n");
fprintf(fp,"\n");

fprintf(fp,"%%!PS-Adobe-3.0 EPSF-3.0\n");
fprintf(fp,"%%%%BoundingBox: 141 609 329 708\n");
fprintf(fp,"%%%%Title: air_coil\n");
fprintf(fp,"%%%%CreationDate: Sat Feb 28 22:32:25 2009\n");
fprintf(fp,"%%%%Creator: Tgif-4.1.45 written by William Chia-Wei Cheng (bill.cheng@acm.org)\n");
fprintf(fp,"%%%%ProducedBy: (unknown)\n");
fprintf(fp,"%%%%Pages: 1\n");
fprintf(fp,"%%%%DocumentFonts: (atend)\n");
fprintf(fp,"%%%%EndComments\n");
fprintf(fp,"%%%%BeginProlog\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifdict 56 dict def\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifarrowtipdict 8 dict def\n");
fprintf(fp,"tgifarrowtipdict /mtrx matrix put\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAT %% tgifarrowtip\n");
fprintf(fp," { tgifarrowtipdict begin\n");
fprintf(fp,"      /dy exch def\n");
fprintf(fp,"      /dx exch def\n");
fprintf(fp,"      /h exch def\n");
fprintf(fp,"      /w exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      dy dx atan rotate\n");
fprintf(fp,"      0 0 moveto\n");
fprintf(fp,"      w neg h lineto\n");
fprintf(fp,"      w neg h neg lineto\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifarcdict 8 dict def\n");
fprintf(fp,"tgifarcdict /mtrx matrix put\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAN %% tgifarcn\n");
fprintf(fp," { tgifarcdict begin\n");
fprintf(fp,"      /endangle exch def\n");
fprintf(fp,"      /startangle exch def\n");
fprintf(fp,"      /yrad exch def\n");
fprintf(fp,"      /xrad exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      xrad yrad scale\n");
fprintf(fp,"      0 0 1 startangle endangle arc\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAR %% tgifarc\n");
fprintf(fp," { tgifarcdict begin\n");
fprintf(fp,"      /endangle exch def\n");
fprintf(fp,"      /startangle exch def\n");
fprintf(fp,"      /yrad exch def\n");
fprintf(fp,"      /xrad exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      xrad yrad scale\n");
fprintf(fp,"      0 0 1 startangle endangle arcn\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGMAX\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll gt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGMIN\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll lt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGSW { stringwidth pop } def\n");
fprintf(fp,"\n");
fprintf(fp,"/bd { bind def } bind def\n");
fprintf(fp,"\n");
fprintf(fp,"/GS { gsave } bd\n");
fprintf(fp,"/GR { grestore } bd\n");
fprintf(fp,"/NP { newpath } bd\n");
fprintf(fp,"/CP { closepath } bd\n");
fprintf(fp,"/CHP { charpath } bd\n");
fprintf(fp,"/CT { curveto } bd\n");
fprintf(fp,"/L { lineto } bd\n");
fprintf(fp,"/RL { rlineto } bd\n");
fprintf(fp,"/M { moveto } bd\n");
fprintf(fp,"/RM { rmoveto } bd\n");
fprintf(fp,"/S { stroke } bd\n");
fprintf(fp,"/F { fill } bd\n");
fprintf(fp,"/TR { translate } bd\n");
fprintf(fp,"/RO { rotate } bd\n");
fprintf(fp,"/SC { scale } bd\n");
fprintf(fp,"/MU { mul } bd\n");
fprintf(fp,"/DI { div } bd\n");
fprintf(fp,"/DU { dup } bd\n");
fprintf(fp,"/NE { neg } bd\n");
fprintf(fp,"/AD { add } bd\n");
fprintf(fp,"/SU { sub } bd\n");
fprintf(fp,"/PO { pop } bd\n");
fprintf(fp,"/EX { exch } bd\n");
fprintf(fp,"/CO { concat } bd\n");
fprintf(fp,"/CL { clip } bd\n");
fprintf(fp,"/EC { eoclip } bd\n");
fprintf(fp,"/EF { eofill } bd\n");
fprintf(fp,"/IM { image } bd\n");
fprintf(fp,"/IMM { imagemask } bd\n");
fprintf(fp,"/ARY { array } bd\n");
fprintf(fp,"/SG { setgray } bd\n");
fprintf(fp,"/RG { setrgbcolor } bd\n");
fprintf(fp,"/SD { setdash } bd\n");
fprintf(fp,"/W { setlinewidth } bd\n");
fprintf(fp,"/SM { setmiterlimit } bd\n");
fprintf(fp,"/SLC { setlinecap } bd\n");
fprintf(fp,"/SLJ { setlinejoin } bd\n");
fprintf(fp,"/SH { show } bd\n");
fprintf(fp,"/FF { findfont } bd\n");
fprintf(fp,"/MS { makefont setfont } bd\n");
fprintf(fp,"/AR { arcto 4 {pop} repeat } bd\n");
fprintf(fp,"/CURP { currentpoint } bd\n");
fprintf(fp,"/FLAT { flattenpath strokepath clip newpath } bd\n");
fprintf(fp,"/TGSM { tgiforigctm setmatrix } def\n");
fprintf(fp,"/TGRM { savematrix setmatrix } def\n");
fprintf(fp,"\n");
fprintf(fp,"end\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%EndProlog\n");
fprintf(fp,"%%%%Page: 1 1\n");
fprintf(fp,"\n");
fprintf(fp,"\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"/tgifsavedpage save def\n");
fprintf(fp,"\n");
fprintf(fp,"1 SM\n");
fprintf(fp,"1 W\n");
fprintf(fp,"\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"\n");
fprintf(fp,"72 0 MU 72 11 MU TR\n");
fprintf(fp,"72 128 DI 100.000 MU 100 DI DU NE SC\n");
fprintf(fp,"\n");
fprintf(fp,"GS\n");
fprintf(fp,"\n");
fprintf(fp,"/tgiforigctm matrix currentmatrix def\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      544 200 M\n");
fprintf(fp,"      112 0 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      112 0 atan DU cos 8.000 MU 544 exch SU\n");
fprintf(fp,"      exch sin 8.000 MU 312 exch SU L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      544 200 8.000 3.000 0 -112 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      544 200 8.000 3.000 0 -112 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      544 312 8.000 3.000 0 112 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      544 312 8.000 3.000 0 112 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 176 M\n");
fprintf(fp,"      0 192 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      0 192 atan DU cos 8.000 MU 496 exch SU\n");
fprintf(fp,"      exch sin 8.000 MU 176 exch SU L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 176 8.000 3.000 -192 0 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 176 8.000 3.000 -192 0 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      496 176 8.000 3.000 192 0 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      496 176 8.000 3.000 192 0 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 200 M\n");
fprintf(fp,"      304 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 383 151 M 420 151 L 420 174 L 383 174 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      384 170 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (Len.) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 551 215 M 582 215 L 582 238 L 551 238 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      552 234 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (I.D.) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      296 196 M\n");
fprintf(fp,"      584 196 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         344 256 40 64 0 -180 TGAR\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         368 256 16 64 180 90 TGAR\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         368 256 16 64 0 90 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         416 256 16 64 180 90 TGAR\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         416 256 16 64 0 90 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 256 M\n");
fprintf(fp,"      256 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   7 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      576 256 M\n");
fprintf(fp,"      536 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   7 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         389 256 37 64 180 225 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         389 256 43 64 -113 0 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         464 256 16 64 180 90 TGAR\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         464 256 16 64 0 90 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         437 256 37 64 180 225 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         437 256 43 64 -113 0 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 256 16 64 180 90 TGAR\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 256 16 64 0 90 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         485 256 37 64 180 225 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         485 256 43 64 -113 0 TGAN\n");
fprintf(fp,"      7 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      520 256 M\n");
fprintf(fp,"      496 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   7 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      296 316 M\n");
fprintf(fp,"      584 316 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      304 168 M\n");
fprintf(fp,"      304 192 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      496 168 M\n");
fprintf(fp,"      496 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"GR\n");
fprintf(fp,"tgifsavedpage restore\n");
fprintf(fp,"end\n");
fprintf(fp,"showpage\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%Trailer\n");
fprintf(fp,"%%MatchingCreationDate: Sat Feb 28 22:32:25 2009\n");
fprintf(fp,"%%%%DocumentFonts: Helvetica\n");
fprintf(fp,"%%%%EOF\n");
fprintf(fp,"\n");
fprintf(fp,"ENDEPSFILE\n");
fprintf(fp,"grestore\n");
fprintf(fp,"moveto\n");

}
/* *********        End of Generated Code           ******** */

