/* $Id: eps2c,v 1.3 2008/11/29 20:42:45 dan Exp $ */

/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with eps2c            ******** */

#include <stdio.h>


void rl_eps(FILE *fp)
{
fprintf(fp,"%% We are currently where the top center of the figure should be.\n");
fprintf(fp,"%% First figure out where the text will be when we continue\n");
fprintf(fp,"%% after the figure\n");
fprintf(fp,"%%\n");
fprintf(fp,"currentpoint 709 612 sub sub\n");
fprintf(fp,"gsave\n");
fprintf(fp,"currentpoint pop 56 368 add 2 div sub\n");
fprintf(fp,"currentpoint exch pop 709 sub \n");
fprintf(fp,"translate\n");
fprintf(fp,"%%\n");
fprintf(fp,"%%include the EPS file\n");
fprintf(fp,"%%\n");
fprintf(fp,"BEGINEPSFILE\n");
fprintf(fp,"\n");

fprintf(fp,"%%!PS-Adobe-3.0 EPSF-3.0\n");
fprintf(fp,"%%%%BoundingBox: 56 612 368 709\n");
fprintf(fp,"%%%%Title: rl\n");
fprintf(fp,"%%%%CreationDate: Sat Feb 28 22:32:26 2009\n");
fprintf(fp,"%%%%Creator: Tgif-4.1.45 written by William Chia-Wei Cheng (bill.cheng@acm.org)\n");
fprintf(fp,"%%%%ProducedBy: (unknown)\n");
fprintf(fp,"%%%%Pages: 1\n");
fprintf(fp,"%%%%DocumentFonts: (atend)\n");
fprintf(fp,"%%%%EndComments\n");
fprintf(fp,"%%%%BeginProlog\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifdict 56 dict def\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifellipsedict 6 dict def\n");
fprintf(fp,"tgifellipsedict /mtrx matrix put\n");
fprintf(fp,"\n");
fprintf(fp,"/TGEL %% tgifellipse\n");
fprintf(fp," { tgifellipsedict begin\n");
fprintf(fp,"      /yrad exch def\n");
fprintf(fp,"      /xrad exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      xrad yrad scale\n");
fprintf(fp,"      0 0 1 0 360 arc\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifarcdict 8 dict def\n");
fprintf(fp,"tgifarcdict /mtrx matrix put\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAN %% tgifarcn\n");
fprintf(fp," { tgifarcdict begin\n");
fprintf(fp,"      /endangle exch def\n");
fprintf(fp,"      /startangle exch def\n");
fprintf(fp,"      /yrad exch def\n");
fprintf(fp,"      /xrad exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      xrad yrad scale\n");
fprintf(fp,"      0 0 1 startangle endangle arc\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAR %% tgifarc\n");
fprintf(fp," { tgifarcdict begin\n");
fprintf(fp,"      /endangle exch def\n");
fprintf(fp,"      /startangle exch def\n");
fprintf(fp,"      /yrad exch def\n");
fprintf(fp,"      /xrad exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      xrad yrad scale\n");
fprintf(fp,"      0 0 1 startangle endangle arcn\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGMAX\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll gt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGMIN\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll lt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGSW { stringwidth pop } def\n");
fprintf(fp,"\n");
fprintf(fp,"/bd { bind def } bind def\n");
fprintf(fp,"\n");
fprintf(fp,"/GS { gsave } bd\n");
fprintf(fp,"/GR { grestore } bd\n");
fprintf(fp,"/NP { newpath } bd\n");
fprintf(fp,"/CP { closepath } bd\n");
fprintf(fp,"/CHP { charpath } bd\n");
fprintf(fp,"/CT { curveto } bd\n");
fprintf(fp,"/L { lineto } bd\n");
fprintf(fp,"/RL { rlineto } bd\n");
fprintf(fp,"/M { moveto } bd\n");
fprintf(fp,"/RM { rmoveto } bd\n");
fprintf(fp,"/S { stroke } bd\n");
fprintf(fp,"/F { fill } bd\n");
fprintf(fp,"/TR { translate } bd\n");
fprintf(fp,"/RO { rotate } bd\n");
fprintf(fp,"/SC { scale } bd\n");
fprintf(fp,"/MU { mul } bd\n");
fprintf(fp,"/DI { div } bd\n");
fprintf(fp,"/DU { dup } bd\n");
fprintf(fp,"/NE { neg } bd\n");
fprintf(fp,"/AD { add } bd\n");
fprintf(fp,"/SU { sub } bd\n");
fprintf(fp,"/PO { pop } bd\n");
fprintf(fp,"/EX { exch } bd\n");
fprintf(fp,"/CO { concat } bd\n");
fprintf(fp,"/CL { clip } bd\n");
fprintf(fp,"/EC { eoclip } bd\n");
fprintf(fp,"/EF { eofill } bd\n");
fprintf(fp,"/IM { image } bd\n");
fprintf(fp,"/IMM { imagemask } bd\n");
fprintf(fp,"/ARY { array } bd\n");
fprintf(fp,"/SG { setgray } bd\n");
fprintf(fp,"/RG { setrgbcolor } bd\n");
fprintf(fp,"/SD { setdash } bd\n");
fprintf(fp,"/W { setlinewidth } bd\n");
fprintf(fp,"/SM { setmiterlimit } bd\n");
fprintf(fp,"/SLC { setlinecap } bd\n");
fprintf(fp,"/SLJ { setlinejoin } bd\n");
fprintf(fp,"/SH { show } bd\n");
fprintf(fp,"/FF { findfont } bd\n");
fprintf(fp,"/MS { makefont setfont } bd\n");
fprintf(fp,"/AR { arcto 4 {pop} repeat } bd\n");
fprintf(fp,"/CURP { currentpoint } bd\n");
fprintf(fp,"/FLAT { flattenpath strokepath clip newpath } bd\n");
fprintf(fp,"/TGSM { tgiforigctm setmatrix } def\n");
fprintf(fp,"/TGRM { savematrix setmatrix } def\n");
fprintf(fp,"\n");
fprintf(fp,"end\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%EndProlog\n");
fprintf(fp,"%%%%Page: 1 1\n");
fprintf(fp,"\n");
fprintf(fp,"\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"/tgifsavedpage save def\n");
fprintf(fp,"\n");
fprintf(fp,"1 SM\n");
fprintf(fp,"1 W\n");
fprintf(fp,"\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"\n");
fprintf(fp,"72 0 MU 72 11 MU TR\n");
fprintf(fp,"72 128 DI 100.000 MU 100 DI DU NE SC\n");
fprintf(fp,"\n");
fprintf(fp,"GS\n");
fprintf(fp,"\n");
fprintf(fp,"/tgiforigctm matrix currentmatrix def\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 284 260 M 484 260 L 484 316 L 284 316 L CP F\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 284 260 M 484 260 L 484 316 L 284 316 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 280 256 M 480 256 L 480 312 L 280 312 L CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 280 256 M 480 256 L 480 312 L 280 312 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 200 M\n");
fprintf(fp,"      272 212 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 236 M\n");
fprintf(fp,"      272 248 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   272 212 M\n");
fprintf(fp,"   264 214 L\n");
fprintf(fp,"   280 218 L\n");
fprintf(fp,"   264 222 L\n");
fprintf(fp,"   280 226 L\n");
fprintf(fp,"   264 230 L\n");
fprintf(fp,"   280 234 L\n");
fprintf(fp,"   272 236 L\n");
fprintf(fp,"CP 1 SG EF\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 212 M\n");
fprintf(fp,"      264 214 L\n");
fprintf(fp,"      280 218 L\n");
fprintf(fp,"      264 222 L\n");
fprintf(fp,"      280 226 L\n");
fprintf(fp,"      264 230 L\n");
fprintf(fp,"      280 234 L\n");
fprintf(fp,"      272 236 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      284 218 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      284 230 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      284 242 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      260 218 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"        GS\n");
fprintf(fp,"        0\n");
fprintf(fp,"            0\n");
fprintf(fp,"        AD\n");
fprintf(fp,"        GR\n");
fprintf(fp,"      NE 0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      260 234 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"        GS\n");
fprintf(fp,"        0\n");
fprintf(fp,"            0\n");
fprintf(fp,"        AD\n");
fprintf(fp,"        GR\n");
fprintf(fp,"      NE 0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 208 M\n");
fprintf(fp,"      240 184 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 248 M\n");
fprintf(fp,"      240 264 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 248 M\n");
fprintf(fp,"      272 264 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 200 M\n");
fprintf(fp,"      272 184 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 256 264 3 3 TGEL F\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 256 264 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 256 184 3 3 TGEL F\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 256 184 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 264 M\n");
fprintf(fp,"      272 264 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      256 264 M\n");
fprintf(fp,"      256 296 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 256 296 3 3 TGEL\n");
fprintf(fp,"CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 256 296 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 184 M\n");
fprintf(fp,"      272 184 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      256 152 M\n");
fprintf(fp,"      256 184 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 256 152 3 3 TGEL\n");
fprintf(fp,"CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 256 152 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 216 M\n");
fprintf(fp,"      512 228 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 252 M\n");
fprintf(fp,"      512 264 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   512 228 M\n");
fprintf(fp,"   504 230 L\n");
fprintf(fp,"   520 234 L\n");
fprintf(fp,"   504 238 L\n");
fprintf(fp,"   520 242 L\n");
fprintf(fp,"   504 246 L\n");
fprintf(fp,"   520 250 L\n");
fprintf(fp,"   512 252 L\n");
fprintf(fp,"CP 1 SG EF\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 228 M\n");
fprintf(fp,"      504 230 L\n");
fprintf(fp,"      520 234 L\n");
fprintf(fp,"      504 238 L\n");
fprintf(fp,"      520 242 L\n");
fprintf(fp,"      504 246 L\n");
fprintf(fp,"      520 250 L\n");
fprintf(fp,"      512 252 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 234 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 246 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 258 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      500 234 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"        GS\n");
fprintf(fp,"        0\n");
fprintf(fp,"            0\n");
fprintf(fp,"        AD\n");
fprintf(fp,"        GR\n");
fprintf(fp,"      NE 0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      500 250 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"        GS\n");
fprintf(fp,"        0\n");
fprintf(fp,"            0\n");
fprintf(fp,"        AD\n");
fprintf(fp,"        GR\n");
fprintf(fp,"      NE 0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 264 M\n");
fprintf(fp,"      512 296 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 152 M\n");
fprintf(fp,"      512 176 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 512 152 3 3 TGEL\n");
fprintf(fp,"CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 512 152 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% OVAL\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 512 296 3 3 TGEL\n");
fprintf(fp,"CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 512 296 3 3 TGEL\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      444 220 M\n");
fprintf(fp,"      484 220 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      444 228 M\n");
fprintf(fp,"      484 228 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      476 212 M\n");
fprintf(fp,"      488 224 L\n");
fprintf(fp,"      476 236 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      452 212 M\n");
fprintf(fp,"      440 224 L\n");
fprintf(fp,"      452 236 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      528 264 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      568 264 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      600 280 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (1 + Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      616 248 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (1) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      600 256 M\n");
fprintf(fp,"      648 256 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   3 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      552 264 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      288 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      328 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      360 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (\\(1 + Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (\\)) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      312 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 200 M\n");
fprintf(fp,"      240 208 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      240 244 M\n");
fprintf(fp,"      240 248 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 222 8 6 -90 90 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 214 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 230 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 223 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 213 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 231 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 221 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 239 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 229 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         240 238 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      252 214 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      252 226 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      252 238 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      252 250 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 168 M\n");
fprintf(fp,"      512 176 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      512 212 M\n");
fprintf(fp,"      512 216 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 190 8 6 -90 90 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 182 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 198 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 191 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 181 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 199 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 189 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 207 10 7 -90 -135 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 197 10 7 90 135 TGAN\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% ARC\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP\n");
fprintf(fp,"         512 206 8 6 90 -90 TGAR\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 182 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 194 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 206 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      524 218 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      304 288 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (Q) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      400 280 M\n");
fprintf(fp,"      440 280 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   3 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      320 288 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      384 288 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      408 304 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      400 272 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Symbol FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (w) SH\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            ( L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      336 280 M\n");
fprintf(fp,"      376 280 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   3 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      344 272 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (R) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      336 304 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Symbol FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (w) SH\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            ( L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      528 192 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      568 192 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      552 192 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      592 208 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (1 + Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      608 176 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      592 184 M\n");
fprintf(fp,"      640 184 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   3 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      104 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (P) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      144 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (L) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 4 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (S) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      128 232 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (=) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      168 216 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (1 + Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      184 248 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (Q) SH\n");
fprintf(fp,"          GS\n");
fprintf(fp,"            GS\n");
fprintf(fp,"              0 -10 RM\n");
fprintf(fp,"              GS\n");
fprintf(fp,"                    0 SG\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) SH\n");
fprintf(fp,"              GR\n");
fprintf(fp,"            GR\n");
fprintf(fp,"          GR\n");
fprintf(fp,"            0\n");
fprintf(fp,"              0\n");
fprintf(fp,"                GS\n");
fprintf(fp,"                0\n");
fprintf(fp,"                    /Helvetica FF [12 0 0 -12 0 0] MS\n");
fprintf(fp,"                    (2) TGSW \n");
fprintf(fp,"                AD\n");
fprintf(fp,"                GR\n");
fprintf(fp,"              TGMAX\n");
fprintf(fp,"            TGMAX\n");
fprintf(fp,"          0 RM\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      168 224 M\n");
fprintf(fp,"      216 224 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   3 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"GR\n");
fprintf(fp,"tgifsavedpage restore\n");
fprintf(fp,"end\n");
fprintf(fp,"showpage\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%Trailer\n");
fprintf(fp,"%%MatchingCreationDate: Sat Feb 28 22:32:26 2009\n");
fprintf(fp,"%%%%DocumentFonts: Symbol\n");
fprintf(fp,"%%%%+ Helvetica\n");
fprintf(fp,"%%%%EOF\n");
fprintf(fp,"\n");
fprintf(fp,"ENDEPSFILE\n");
fprintf(fp,"grestore\n");
fprintf(fp,"moveto\n");

}
/* *********        End of Generated Code           ******** */

