/* $Id: eps2c,v 1.3 2008/11/29 20:42:45 dan Exp $ */

/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with eps2c            ******** */

#include <stdio.h>


void splash_eps(FILE *fp)
{
fprintf(fp,"%% We are currently where the top center of the figure should be.\n");
fprintf(fp,"%% First figure out where the text will be when we continue\n");
fprintf(fp,"%% after the figure\n");
fprintf(fp,"%%\n");
fprintf(fp,"currentpoint 766 673 sub sub\n");
fprintf(fp,"gsave\n");
fprintf(fp,"currentpoint pop 101 307 add 2 div sub\n");
fprintf(fp,"currentpoint exch pop 766 sub \n");
fprintf(fp,"translate\n");
fprintf(fp,"%%\n");
fprintf(fp,"%%include the EPS file\n");
fprintf(fp,"%%\n");
fprintf(fp,"BEGINEPSFILE\n");
fprintf(fp,"\n");

fprintf(fp,"%%!PS-Adobe-3.0 EPSF-3.0\n");
fprintf(fp,"%%%%BoundingBox: 101 673 307 766\n");
fprintf(fp,"%%%%Title: splash\n");
fprintf(fp,"%%%%CreationDate: Sat Feb 28 22:32:27 2009\n");
fprintf(fp,"%%%%Creator: Tgif-4.1.45 written by William Chia-Wei Cheng (bill.cheng@acm.org)\n");
fprintf(fp,"%%%%ProducedBy: (unknown)\n");
fprintf(fp,"%%%%Pages: 1\n");
fprintf(fp,"%%%%DocumentFonts: (atend)\n");
fprintf(fp,"%%%%EndComments\n");
fprintf(fp,"%%%%BeginProlog\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifdict 81 dict def\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatdict 10 dict def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatbyte\n");
fprintf(fp," { currentdict /retstr get exch\n");
fprintf(fp,"   pat i cellsz mod get put\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatproc\n");
fprintf(fp," { 0 1 widthlim {tgifpatbyte} for retstr\n");
fprintf(fp,"   /i i 1 add def\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGPF %% tgifpatfill\n");
fprintf(fp," { tgifpatdict begin\n");
fprintf(fp,"      /h exch def\n");
fprintf(fp,"      /w exch def\n");
fprintf(fp,"      /lty exch def\n");
fprintf(fp,"      /ltx exch def\n");
fprintf(fp,"      /cellsz exch def\n");
fprintf(fp,"      /pat exch def\n");
fprintf(fp,"\n");
fprintf(fp,"      /widthlim w cellsz div cvi 1 sub def\n");
fprintf(fp,"      /retstr widthlim 1 add string def\n");
fprintf(fp,"      /i 0 def\n");
fprintf(fp,"\n");
fprintf(fp,"      tgiforigctm setmatrix\n");
fprintf(fp,"      ltx lty translate\n");
fprintf(fp,"      w h true [1 0 0 1 0 0] {tgifpatproc} imagemask\n");
fprintf(fp,"      ltx neg lty neg translate\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/pat3 <8000000008000000> def\n");
fprintf(fp,"/pat4 <8800000022000000> def\n");
fprintf(fp,"/pat5 <8800220088002200> def\n");
fprintf(fp,"/pat6 <8822882288228822> def\n");
fprintf(fp,"/pat7 <aa55aa55aa55aa55> def\n");
fprintf(fp,"/pat8 <77dd77dd77dd77dd> def\n");
fprintf(fp,"/pat9 <77ffddff77ffddff> def\n");
fprintf(fp,"/pat10 <77ffffff77ffffff> def\n");
fprintf(fp,"/pat11 <7fffffff7fffffff> def\n");
fprintf(fp,"/pat12 <8040200002040800> def\n");
fprintf(fp,"/pat13 <40a00000040a0000> def\n");
fprintf(fp,"/pat14 <ff888888ff888888> def\n");
fprintf(fp,"/pat15 <ff808080ff080808> def\n");
fprintf(fp,"/pat16 <f87422478f172271> def\n");
fprintf(fp,"/pat17 <038448300c020101> def\n");
fprintf(fp,"/pat18 <081c22c180010204> def\n");
fprintf(fp,"/pat19 <8080413e080814e3> def\n");
fprintf(fp,"/pat20 <8040201008040201> def\n");
fprintf(fp,"/pat21 <8844221188442211> def\n");
fprintf(fp,"/pat22 <77bbddee77bbddee> def\n");
fprintf(fp,"/pat23 <c1e070381c0e0783> def\n");
fprintf(fp,"/pat24 <7fbfdfeff7fbfdfe> def\n");
fprintf(fp,"/pat25 <3e1f8fc7e3f1f87c> def\n");
fprintf(fp,"/pat26 <0102040810204080> def\n");
fprintf(fp,"/pat27 <1122448811224488> def\n");
fprintf(fp,"/pat28 <eeddbb77eeddbb77> def\n");
fprintf(fp,"/pat29 <83070e1c3870e0c1> def\n");
fprintf(fp,"/pat30 <fefdfbf7efdfbf7f> def\n");
fprintf(fp,"/pat31 <7cf8f1e3c78f1f3e> def\n");
fprintf(fp,"\n");
fprintf(fp,"/bd { bind def } bind def\n");
fprintf(fp,"\n");
fprintf(fp,"/GS { gsave } bd\n");
fprintf(fp,"/GR { grestore } bd\n");
fprintf(fp,"/NP { newpath } bd\n");
fprintf(fp,"/CP { closepath } bd\n");
fprintf(fp,"/CHP { charpath } bd\n");
fprintf(fp,"/CT { curveto } bd\n");
fprintf(fp,"/L { lineto } bd\n");
fprintf(fp,"/RL { rlineto } bd\n");
fprintf(fp,"/M { moveto } bd\n");
fprintf(fp,"/RM { rmoveto } bd\n");
fprintf(fp,"/S { stroke } bd\n");
fprintf(fp,"/F { fill } bd\n");
fprintf(fp,"/TR { translate } bd\n");
fprintf(fp,"/RO { rotate } bd\n");
fprintf(fp,"/SC { scale } bd\n");
fprintf(fp,"/MU { mul } bd\n");
fprintf(fp,"/DI { div } bd\n");
fprintf(fp,"/DU { dup } bd\n");
fprintf(fp,"/NE { neg } bd\n");
fprintf(fp,"/AD { add } bd\n");
fprintf(fp,"/SU { sub } bd\n");
fprintf(fp,"/PO { pop } bd\n");
fprintf(fp,"/EX { exch } bd\n");
fprintf(fp,"/CO { concat } bd\n");
fprintf(fp,"/CL { clip } bd\n");
fprintf(fp,"/EC { eoclip } bd\n");
fprintf(fp,"/EF { eofill } bd\n");
fprintf(fp,"/IM { image } bd\n");
fprintf(fp,"/IMM { imagemask } bd\n");
fprintf(fp,"/ARY { array } bd\n");
fprintf(fp,"/SG { setgray } bd\n");
fprintf(fp,"/RG { setrgbcolor } bd\n");
fprintf(fp,"/SD { setdash } bd\n");
fprintf(fp,"/W { setlinewidth } bd\n");
fprintf(fp,"/SM { setmiterlimit } bd\n");
fprintf(fp,"/SLC { setlinecap } bd\n");
fprintf(fp,"/SLJ { setlinejoin } bd\n");
fprintf(fp,"/SH { show } bd\n");
fprintf(fp,"/FF { findfont } bd\n");
fprintf(fp,"/MS { makefont setfont } bd\n");
fprintf(fp,"/AR { arcto 4 {pop} repeat } bd\n");
fprintf(fp,"/CURP { currentpoint } bd\n");
fprintf(fp,"/FLAT { flattenpath strokepath clip newpath } bd\n");
fprintf(fp,"/TGSM { tgiforigctm setmatrix } def\n");
fprintf(fp,"/TGRM { savematrix setmatrix } def\n");
fprintf(fp,"\n");
fprintf(fp,"end\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%EndProlog\n");
fprintf(fp,"%%%%Page: 1 1\n");
fprintf(fp,"\n");
fprintf(fp,"\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"/tgifsavedpage save def\n");
fprintf(fp,"\n");
fprintf(fp,"1 SM\n");
fprintf(fp,"1 W\n");
fprintf(fp,"\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"\n");
fprintf(fp,"72 0 MU 72 11 MU TR\n");
fprintf(fp,"72 128 DI 100.000 MU 100 DI DU NE SC\n");
fprintf(fp,"\n");
fprintf(fp,"GS\n");
fprintf(fp,"\n");
fprintf(fp,"/tgiforigctm matrix currentmatrix def\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 128 M\n");
fprintf(fp,"      448 128 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 192 M\n");
fprintf(fp,"      448 192 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"1.000 0.000 0.000 RG\n");
fprintf(fp,"NP 272 112 M 368 112 L 368 128 L 272 128 L CP F\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 272 112 M 368 112 L 368 128 L 272 128 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 112 M\n");
fprintf(fp,"      472 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 128 M\n");
fprintf(fp,"      288 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      448 128 M\n");
fprintf(fp,"      544 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 128 M\n");
fprintf(fp,"      472 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      376 48 M\n");
fprintf(fp,"      472 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 48 M\n");
fprintf(fp,"      472 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 112 M\n");
fprintf(fp,"      376 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 64 M\n");
fprintf(fp,"      544 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      288 64 M\n");
fprintf(fp,"      352 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP 184 192 M 448 192 L 448 208 L 184 208 L CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP 184 192 M 448 192 L 448 208 L 184 208 L CP EC NP\n");
fprintf(fp,"   pat6 8 176 184 280 32 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 184 192 M 448 192 L 448 208 L 184 208 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   448 192 M\n");
fprintf(fp,"   544 128 L\n");
fprintf(fp,"   544 144 L\n");
fprintf(fp,"   448 208 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat6 8 440 120 112 96 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0.000 0.000 1.000 RG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   184 128 M\n");
fprintf(fp,"   184 192 L\n");
fprintf(fp,"   448 192 L\n");
fprintf(fp,"   544 128 L\n");
fprintf(fp,"   544 64 L\n");
fprintf(fp,"   448 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      448 128 M\n");
fprintf(fp,"      448 192 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"1.000 0.000 0.000 RG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 112 M\n");
fprintf(fp,"   368 128 L\n");
fprintf(fp,"   472 64 L\n");
fprintf(fp,"   472 48 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"1.000 0.000 0.000 RG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 112 M\n");
fprintf(fp,"   472 48 L\n");
fprintf(fp,"   376 48 L\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0.000 0.000 1.000 RG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 128 M\n");
fprintf(fp,"   472 64 L\n");
fprintf(fp,"   544 64 L\n");
fprintf(fp,"   448 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0.000 0.000 1.000 RG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   272 128 M\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"   352 64 L\n");
fprintf(fp,"   280 64 L\n");
fprintf(fp,"   184 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 112 M\n");
fprintf(fp,"   472 48 L\n");
fprintf(fp,"   376 48 L\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   2 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 272 112 M 368 112 L 368 128 L 272 128 L CP\n");
fprintf(fp,"      2 W\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   272 128 M\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"   352 64 L\n");
fprintf(fp,"   280 64 L\n");
fprintf(fp,"   184 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   2 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 128 M\n");
fprintf(fp,"   472 64 L\n");
fprintf(fp,"   544 64 L\n");
fprintf(fp,"   448 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   2 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"GR\n");
fprintf(fp,"tgifsavedpage restore\n");
fprintf(fp,"end\n");
fprintf(fp,"showpage\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%Trailer\n");
fprintf(fp,"%%MatchingCreationDate: Sat Feb 28 22:32:27 2009\n");
fprintf(fp,"%%%%DocumentFonts: \n");
fprintf(fp,"%%%%EOF\n");
fprintf(fp,"\n");
fprintf(fp,"ENDEPSFILE\n");
fprintf(fp,"grestore\n");
fprintf(fp,"moveto\n");

}
/* *********        End of Generated Code           ******** */

