
/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(cgiOut,"<!-- $Id: air_coil.html,v 1.18 2009/02/11 00:00:26 dan Exp $ -->\n");
fprintf(cgiOut,"<!--\n");
fprintf(cgiOut," * Copyright (c) 2001, 2002, 2004, 2005 Dan McMahill\n");
fprintf(cgiOut," * All rights reserved.\n");
fprintf(cgiOut," *\n");
fprintf(cgiOut," * This program is free software; you can redistribute it and/or modify\n");
fprintf(cgiOut," * it under the terms of the GNU General Public License as published by\n");
fprintf(cgiOut," * the Free Software Foundation; version 2 of the License.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * This program is distributed in the hope that it will be useful,\n");
fprintf(cgiOut," * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
fprintf(cgiOut," * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
fprintf(cgiOut," * GNU General Public License for more details.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * You should have received a copy of the GNU General Public License\n");
fprintf(cgiOut," * along with this program; if not, write to the Free Software\n");
fprintf(cgiOut," * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n");
fprintf(cgiOut," -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n");
fprintf(cgiOut,"<HTML>\n");
fprintf(cgiOut,"<HEAD>\n");
fprintf(cgiOut,"<TITLE>Air Core Inductor Analysis/Synthesis</TITLE>\n");
fprintf(cgiOut,"<!-- Created by: Dan McMahill, 2001/09/13 -->\n");
fprintf(cgiOut,"<LINK REV=\"made\" HREF=\"mailto:nospam_to_mcmahill@alum.mit.make_edu\">\n");
fprintf(cgiOut,"<link rel=\"shortcut icon\" href=\"%s/favicon.ico\" type=\"image/x-icon\">    \n",HTMLPATH);
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
fprintf(cgiOut,"<meta name=\"description\" content=\"Air Core Inductor Analysis/Synthesis\">\n");
fprintf(cgiOut,"<meta name=\"keywords\" content=\"\n");
fprintf(cgiOut,"Air Core Inductor\n");
fprintf(cgiOut,"\">\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_init());
fprintf(cgiOut,"</HEAD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<body bgcolor=\"#FFFFFF\" text=\"#000000\" onLoad=\"units_init()\">\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<H1 ALIGN=\"CENTER\">Air Core Inductor Analysis/Synthesis Calculator</H1>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<P>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<FORM NAME=\"wcalc\" METHOD=GET ACTION=\"air_coil.cgi\">\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><IMG SRC=\"%sair_coil.png\" WIDTH=332 HEIGHT=173\n",HTMLPATH);
fprintf(cgiOut,"     ALT=\"[Air Core Inductor Drawing]\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"<!--\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><IMG SRC=\"%sair_coil_model.png\" \n",HTMLPATH);
fprintf(cgiOut,"     ALT=\"[Air Core Inductor Circuit Model]\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"-->\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" DISABLED NAME=\"status\" VALUE=\" \"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Q =</TD>\n");
fprintf(cgiOut,"<TD>%g @ %g</TD>\n",coil->Q,coil->freq/coil->units_freq->sf);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_Qfreq\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Self Resonant Freq =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",coil->SRF/coil->units_SRF->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_SRF));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Max Inductance =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",coil->Lmax/coil->units_L->sf);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_Lmax\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Length/Min Length =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",coil->fill);
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end of model parameter table -->\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end left hand 1/2 of main table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Number of turns (N)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"N\" VALUE=\"%g\"\n",coil->Nf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_n\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Inside Diameter (I.D.)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"dia\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",coil->dia/coil->units_dia->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- dia units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_dia));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"RADIO\" NAME=\"use_fill\" VALUE=\"no\" \n");
fprintf(cgiOut,"%s\n",coil->use_fill == 0 ? "CHECKED" : "");
fprintf(cgiOut,"        onChange=\"valsChanged()\">Solenoid length (L)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"len\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",coil->len/coil->units_len->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- length units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_len));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_nfix\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"RADIO\" NAME=\"use_fill\" VALUE=\"yes\" \n");
fprintf(cgiOut,"%s\n",coil->use_fill == 1 ? "CHECKED" : "");
fprintf(cgiOut,"        onChange=\"valsChanged()\">Fill (L/Lmin)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"fill\" VALUE=\"%g\"\n",coil->fill);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Wire Size</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"AWG\" VALUE=\"%g\"\n",coil->AWGf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[<A HREF=\"%sAWG.html\">AWG</A>]</TD>\n",HTMLPATH);
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%sresistivity.html\">Metal resistivity</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"rho\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",coil->rho/coil->units_rho->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_rho));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Frequency</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"freq\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",coil->freq/coil->units_freq->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- frequency units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_freq));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"analyze\" VALUE=\"Analyze\">\n");
fprintf(cgiOut,"<INPUT TYPE=\"SUBMIT\" NAME=\"reset\" VALUE=\"Reset\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Inductance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"L\" VALUE=\"%g\"\n",coil->L/coil->units_L->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- inductance units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_L));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</FORM>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");

/* *********        End of Generated Code           ******** */

