
/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(cgiOut,"<!-- $Id: bars.html,v 1.4 2009/02/11 00:00:27 dan Exp $ -->\n");
fprintf(cgiOut,"<!--\n");
fprintf(cgiOut," * Copyright (c) 2009 Dan McMahill\n");
fprintf(cgiOut," * All rights reserved.\n");
fprintf(cgiOut," *\n");
fprintf(cgiOut," * This program is free software; you can redistribute it and/or modify\n");
fprintf(cgiOut," * it under the terms of the GNU General Public License as published by\n");
fprintf(cgiOut," * the Free Software Foundation; version 2 of the License.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * This program is distributed in the hope that it will be useful,\n");
fprintf(cgiOut," * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
fprintf(cgiOut," * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
fprintf(cgiOut," * GNU General Public License for more details.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * You should have received a copy of the GNU General Public License\n");
fprintf(cgiOut," * along with this program; if not, write to the Free Software\n");
fprintf(cgiOut," * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n");
fprintf(cgiOut," -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n");
fprintf(cgiOut,"<HTML>\n");
fprintf(cgiOut,"<HEAD>\n");
fprintf(cgiOut,"<TITLE>Self/Mutual Inductance of a Pair of Rectangular Bars</TITLE>\n");
fprintf(cgiOut,"<!-- Created by: Dan McMahill, 2009/01/10 -->\n");
fprintf(cgiOut,"<LINK REV=\"made\" HREF=\"mailto:nospam_to_mcmahill@alum.mit.make_edu\">\n");
fprintf(cgiOut,"<link rel=\"shortcut icon\" href=\"%s/favicon.ico\" type=\"image/x-icon\">    \n",HTMLPATH);
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
fprintf(cgiOut,"<meta name=\"description\" content=\"Self and Mutual Inductance of a Pair of Parallel Rectangular Bars\">\n");
fprintf(cgiOut,"<meta name=\"keywords\" content=\"\n");
fprintf(cgiOut,"mutual inductance,\n");
fprintf(cgiOut,"parallel bars,\n");
fprintf(cgiOut,"inductance of parallel bars,\n");
fprintf(cgiOut,"mutual inductance of parallel bars\n");
fprintf(cgiOut,"\">\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_init());
fprintf(cgiOut,"</HEAD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<body bgcolor=\"#FFFFFF\" text=\"#000000\" onLoad=\"units_init()\">\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<H1 ALIGN=\"CENTER\">Parallel Rectangular Bars Self/Mutual Inductance</H1>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<P>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<FORM NAME=\"wcalc\" METHOD=GET ACTION=\"bars.cgi\">\n");
fprintf(cgiOut,"  <TABLE>\n");
fprintf(cgiOut,"    <TR>\n");
fprintf(cgiOut,"      <TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"        <TABLE>\n");
fprintf(cgiOut,"          <TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"            <TD><IMG SRC=\"%sbars_fig.png\" WIDTH=593 HEIGHT=185\n",HTMLPATH);
fprintf(cgiOut,"                 ALT=\"[Parallel Rectangular Bars Drawing]\"></TD>\n");
fprintf(cgiOut,"          </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"          <TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"            <TD><INPUT TYPE=\"TEXT\" DISABLED NAME=\"status\" VALUE=\" \"></TD>\n");
fprintf(cgiOut,"          </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"          <TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"            <TD>\n");
fprintf(cgiOut,"              <TABLE>\n");
fprintf(cgiOut,"                <TR>\n");
fprintf(cgiOut,"                  <TD>Frequency</TD>\n");
fprintf(cgiOut,"                  <TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"freq\" \n");
fprintf(cgiOut,"                       VALUE=\"%g\"\n",bar->freq/bar->units_freq->sf);
fprintf(cgiOut,"                       onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"                  <TD>\n");
fprintf(cgiOut,"                    <!-- frequency units menu -->\n");
fprintf(cgiOut,"                    %s\n",cgi_units_menu_display(menu_freq));
fprintf(cgiOut,"                  </TD>\n");
fprintf(cgiOut,"                </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"              </TABLE>  <!-- end of model parameter table -->\n");
fprintf(cgiOut,"            </TD>\n");
fprintf(cgiOut,"          </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"        </TABLE>  <!-- end left hand 1/2 of main table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"      <TD>\n");
fprintf(cgiOut,"        <TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"                <TR>\n");
fprintf(cgiOut,"                  <TD>Width of Bar #1 (a)</TD>\n");
fprintf(cgiOut,"                  <TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"a\" \n");
fprintf(cgiOut,"                       VALUE=\"%g\"\n",bar->a/bar->units_xy->sf);
fprintf(cgiOut,"                       onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"                  <TD>\n");
fprintf(cgiOut,"                    <!-- xy units menu -->\n");
fprintf(cgiOut,"                    %s\n",cgi_units_menu_display(menu_xy));
fprintf(cgiOut,"                  </TD>\n");
fprintf(cgiOut,"                </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"                <TR>\n");
fprintf(cgiOut,"                  <TD>Thickness of Bar #1 (b)</TD>\n");
fprintf(cgiOut,"                  <TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"b\" \n");
fprintf(cgiOut,"                       VALUE=\"%g\"\n",bar->b/bar->units_xy->sf);
fprintf(cgiOut,"                       onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"                  <TD>\n");
fprintf(cgiOut,"                    <INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_b\">\n");
fprintf(cgiOut,"                  </TD>\n");
fprintf(cgiOut,"                </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"                <TR>\n");
fprintf(cgiOut,"                  <TD>Length of Bar #1 (l1)</TD>\n");
fprintf(cgiOut,"                  <TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"l1\" \n");
fprintf(cgiOut,"                       VALUE=\"%g\"\n",bar->l1/bar->units_xy->sf);
fprintf(cgiOut,"                       onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"                  <TD>\n");
fprintf(cgiOut,"                    <INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_l1\">\n");
fprintf(cgiOut,"                  </TD>\n");
fprintf(cgiOut,"                </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Width of Bar #2 (d)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"d\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->d/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_d\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Thickness of Bar #2 (c)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"c\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->c/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_c\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Length of Bar #2 (L2)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"l2\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->l2/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_l2\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Bar #2 Width Position (E)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"E\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->E/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_E\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Bar #2 Thickness Position (P)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"P\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->P/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_P\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Bar #2 Length Position (L3)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"l3\" \n");
fprintf(cgiOut,"     VALUE=\"%g\"\n",bar->l3/bar->units_xy->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_l3\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"                <TR>\n");
fprintf(cgiOut,"                  <TD><INPUT TYPE=\"SUBMIT\" NAME=\"analyze\" VALUE=\"Analyze\">\n");
fprintf(cgiOut,"                    <INPUT TYPE=\"SUBMIT\" NAME=\"reset\" VALUE=\"Reset\"></TD>\n");
fprintf(cgiOut,"                  <TD></TD>\n");
fprintf(cgiOut,"                </TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR><TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Bar #1 Self Inductance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"L1\" VALUE=\"%g\"\n",bar->L1/bar->units_L->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- inductance units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_L));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"<TD>Bar #2 Self Inductance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"L2\" VALUE=\"%g\"\n",bar->L2/bar->units_L->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_L2\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Mutual Inductance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"M\" VALUE=\"%g\"\n",bar->M/bar->units_L->sf);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_M\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD>Coupling Coefficient</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"k\" VALUE=\"%g\"\n",bar->k);
fprintf(cgiOut,"        onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</FORM>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");

/* *********        End of Generated Code           ******** */

