
/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(cgiOut,"<!-- $Id: coax.html,v 1.16 2009/02/11 00:00:27 dan Exp $ -->\n");
fprintf(cgiOut,"<!--\n");
fprintf(cgiOut," * Copyright (c) 2002, 2004, 2005 Dan McMahill\n");
fprintf(cgiOut," * All rights reserved.\n");
fprintf(cgiOut," *\n");
fprintf(cgiOut," * This program is free software; you can redistribute it and/or modify\n");
fprintf(cgiOut," * it under the terms of the GNU General Public License as published by\n");
fprintf(cgiOut," * the Free Software Foundation; version 2 of the License.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * This program is distributed in the hope that it will be useful,\n");
fprintf(cgiOut," * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
fprintf(cgiOut," * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
fprintf(cgiOut," * GNU General Public License for more details.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * You should have received a copy of the GNU General Public License\n");
fprintf(cgiOut," * along with this program; if not, write to the Free Software\n");
fprintf(cgiOut," * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n");
fprintf(cgiOut," -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n");
fprintf(cgiOut,"<HTML>\n");
fprintf(cgiOut,"<HEAD>\n");
fprintf(cgiOut,"<TITLE>Coax Analysis/Synthesis</TITLE>\n");
fprintf(cgiOut,"<!-- Created by: Dan McMahill, 2001/09/12 -->\n");
fprintf(cgiOut,"<LINK REV=\"made\" HREF=\"mailto:nospam_to_mcmahill@alum.mit.make_edu\">\n");
fprintf(cgiOut,"<link rel=\"shortcut icon\" href=\"%s/favicon.ico\" type=\"image/x-icon\">    \n",HTMLPATH);
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
fprintf(cgiOut,"<meta name=\"description\" content=\"Coax Analysis/Synthesis\">\n");
fprintf(cgiOut,"<meta name=\"keywords\" content=\"\n");
fprintf(cgiOut,"coax\n");
fprintf(cgiOut,"\">\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_init());
fprintf(cgiOut,"</HEAD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<body bgcolor=\"#FFFFFF\" text=\"#000000\" onLoad=\"units_init()\">\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<H1 ALIGN=\"CENTER\">Coax Analysis/Synthesis Calculator</H1>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<P>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<FORM NAME=\"wcalc\" METHOD=GET ACTION=\"coax.cgi\">\n");
fprintf(cgiOut,"<TABLE> <!-- The main table -->\n");
fprintf(cgiOut,"<TR>    <!-- The first (only) row in the main table -->\n");
fprintf(cgiOut,"<TD>    <!-- The left hand cell in the main table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>  <!-- The left hand table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><IMG SRC=\"%scoax_model.png\"  WIDTH=287 HEIGHT=125\n",HTMLPATH);
fprintf(cgiOut,"     ALT=\"[Coax Circuit Model]\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" DISABLED NAME=\"status\" VALUE=\" \"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>  <!-- The left hand entry table -->\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>L =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->L/line->units_L->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_L));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>R =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->R/line->units_R->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_R));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>C =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->C/line->units_C->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_C));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>G =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->G/line->units_G->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_G));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Z0 =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->z0);
fprintf(cgiOut,"<TD>[ohm]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Loss =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->loss);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_loss));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Loss/len =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->losslen);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_losslen));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Conductor Loss =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->alpha_c/line->units_losslen->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_alphac\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Dielectric Loss =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->alpha_d/line->units_losslen->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_alphad\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Delay =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->delay/line->units_delay->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_delay));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>TE10 Cutoff Freq. =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->fc/line->units_fc->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_fc));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Max. E-Field =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->emax/line->units_emax->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_emax));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end of model parameter table -->\n");
fprintf(cgiOut,"</TD>     <!-- end of cell with left hand entry table -->\n");
fprintf(cgiOut,"</TR>     <!-- end of row with left hand entry table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end left hand table -->\n");
fprintf(cgiOut,"</TD>     <!-- end cell in main table holding left hand side -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD>      <!-- right hand cell -->\n");
fprintf(cgiOut,"<TABLE>   <!-- right hand table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><IMG SRC=\"%scoax.png\" WIDTH=327 HEIGHT=243\n",HTMLPATH);
fprintf(cgiOut,"     ALT=\"[Coax Cross-section]\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>  <!-- right hand entry table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Inner Radius (A)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"a\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->a/line->units_abct->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- A units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_abct));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_a\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Outer Radius (B)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"b\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->b/line->units_abct->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- B units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_b\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_b\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Offset (C)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"c\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->c/line->units_abct->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- C units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_c\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_c\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Shield Thickness (T)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"tshield\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->tshield/line->units_abct->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- Tshield units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_t\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Line length (L)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"len\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->len/line->units_len->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- length units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_len));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%sresistivity.html\">Metal resistivity (RHOA)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"rhoa\" \n");
fprintf(cgiOut,"  VALUE=\"%g\"\n",line->rho_a/line->units_rho->sf);
fprintf(cgiOut,"  onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- Resistivity units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_rho));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%sresistivity.html\">Metal resistivity (RHOB)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"rhob\"\n");
fprintf(cgiOut,"  VALUE=\"%g\" \n",line->rho_b/line->units_rho->sf);
fprintf(cgiOut,"  onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_rhob\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%spermitivity.html\">Relative dielectric constant (Er)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"er\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->er);
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_er\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%spermitivity.html\">Dielectric loss tangent (tand)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"tand\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->tand);
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Frequency</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"freq\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->freq/line->units_freq->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- freq units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_freq));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"analyze\" VALUE=\"Analyze\">\n");
fprintf(cgiOut,"<INPUT TYPE=\"SUBMIT\" NAME=\"reset\" VALUE=\"Reset\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Characteristic Impedance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"Ro\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->z0);
fprintf(cgiOut,"<TD>[ohms]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Electrical Length</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"elen\" VALUE=\"%g\" onChange=\"valsChanged()\"></TD>\n",line->elen);
fprintf(cgiOut,"<TD>[degrees]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- The values table in the right side -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TD>     <!-- The cell in the right hand table with the values table -->\n");
fprintf(cgiOut,"</TR>     <!-- The row in the right hand table with the values table -->\n");
fprintf(cgiOut,"</TABLE>  <!-- The right hand table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TD>     <!-- The cell with the right hand table -->\n");
fprintf(cgiOut,"</TR>     <!-- The row in the main table -->\n");
fprintf(cgiOut,"</TABLE>  <!-- The main table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</FORM>\n");
fprintf(cgiOut,"\n");

/* *********        End of Generated Code           ******** */

