
/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(cgiOut,"<!-- $Id: coupled_stripline.html,v 1.5 2009/02/11 00:00:28 dan Exp $ -->\n");
fprintf(cgiOut,"<!--\n");
fprintf(cgiOut," * Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006 Dan McMahill\n");
fprintf(cgiOut," * All rights reserved.\n");
fprintf(cgiOut," *\n");
fprintf(cgiOut," * This program is free software; you can redistribute it and/or modify\n");
fprintf(cgiOut," * it under the terms of the GNU General Public License as published by\n");
fprintf(cgiOut," * the Free Software Foundation; version 2 of the License.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * This program is distributed in the hope that it will be useful,\n");
fprintf(cgiOut," * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
fprintf(cgiOut," * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
fprintf(cgiOut," * GNU General Public License for more details.\n");
fprintf(cgiOut," * \n");
fprintf(cgiOut," * You should have received a copy of the GNU General Public License\n");
fprintf(cgiOut," * along with this program; if not, write to the Free Software\n");
fprintf(cgiOut," * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n");
fprintf(cgiOut," -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n");
fprintf(cgiOut,"<HTML>\n");
fprintf(cgiOut,"<HEAD>\n");
fprintf(cgiOut,"<TITLE>Coupled Stripline Analysis/Synthesis</TITLE>\n");
fprintf(cgiOut,"<!-- Created by: Dan McMahill, 2001/09/12 -->\n");
fprintf(cgiOut,"<LINK REV=\"made\" HREF=\"mailto:nospam_to_mcmahill@alum.mit.make_edu\">\n");
fprintf(cgiOut,"<link rel=\"shortcut icon\" href=\"%s/favicon.ico\" type=\"image/x-icon\">    \n",HTMLPATH);
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
fprintf(cgiOut,"<meta name=\"description\" content=\"Coupled Stripline Analysis/Synthesis\">\n");
fprintf(cgiOut,"<meta name=\"keywords\" content=\"\n");
fprintf(cgiOut,"coupled microstrip\n");
fprintf(cgiOut,"\">\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_init());
fprintf(cgiOut,"</HEAD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<body bgcolor=\"#FFFFFF\" text=\"#000000\" onLoad=\"units_init()\">\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<H1 ALIGN=\"CENTER\">Coupled Stripline Analysis/Synthesis Calculator</H1>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<P>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<FORM NAME=\"wcalc\" METHOD=GET ACTION=\"coupled_stripline.cgi\">\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><IMG SRC=\"%scoupled_stripline.png\" WIDTH=433 HEIGHT=168\n",HTMLPATH);
fprintf(cgiOut,"     ALT=\"[Coupled Stripline Cross-section]\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" DISABLED NAME=\"status\" VALUE=\" \"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR ALIGN=\"CENTER\">\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Zeven =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->z0e);
fprintf(cgiOut,"<TD>[ohm]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Zodd =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->z0o);
fprintf(cgiOut,"<TD>[ohm]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Z0 =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->z0);
fprintf(cgiOut,"<TD>[ohm]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>coupling =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->k);
fprintf(cgiOut,"<TD>[-]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>coupling =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",20.0*log10(line->k));
fprintf(cgiOut,"<TD>[dB]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Even mode Loss =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->loss_ev/line->units_loss->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_loss));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Odd mode Loss =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->loss_odd/line->units_loss->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\"dB\" NAME=\"entry_loss_odd\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Even mode Loss/len =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->losslen_ev/line->units_losslen->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_losslen));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Odd mode Loss/len =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->losslen_odd/line->units_losslen->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_losslen_odd\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Skin depth =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->skindepth/line->units_depth->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_depth));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Delay =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->delay/line->units_delay->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_delay));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Even mode delta L =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->deltale/line->units_deltal->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_deltal));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Odd mode delta L =</TD>\n");
fprintf(cgiOut,"<TD>%g</TD>\n",line->deltalo/line->units_deltal->sf);
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_deltal\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end of model parameter table -->\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>  <!-- end left hand 1/2 of main table -->\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Metal width (W)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"w\" VALUE=\"%g\"\n",line->w/line->units_lwst->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_lwst));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"synth_w\" VALUE=\"calc\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Trace spacing (S)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"s\" VALUE=\"%g\"\n",line->s/line->units_lwst->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- spacing units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_s\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Trace length (L)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"l\" VALUE=\"%g\"\n",line->l/line->units_lwst->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- length units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_l\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"/cad/mcalc/tmetinfo.html\">Metal thickness (Tmet)</A></TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"tmet\" VALUE=\"%g\"\n",line->subs->tmet/line->units_lwst->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- Tmet units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_tmet\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%sresistivity.html\">Metal resistivity (Rho)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"rho\" VALUE=\"%g\"\n",line->subs->rho/line->units_rho->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- Rho units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_rho));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"/cad/mcalc/rghinfo.html\">Metal surface roughness (Rgh)</A></TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"rough\" VALUE=\"%g\"\n",line->subs->rough/line->units_rough->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- surface roughness units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_rough));
fprintf(cgiOut,"-RMS\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Substrate thickness (H)</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"h\" VALUE=\"%g\"\n",line->subs->h/line->units_lwst->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- substrate thickness units menu -->\n");
fprintf(cgiOut,"<INPUT TYPE=\"TEXT\" DISABLED VALUE=\" \" NAME=\"entry_h\">\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%spermitivity.html\">Substrate relative dielectric constant (er)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"es\" VALUE=\"%g\"\n",line->subs->er);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><A HREF=\"%spermitivity.html\">Substrate loss tangent (tand)</A></TD>\n",HTMLPATH);
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"tand\" VALUE=\"%g\"\n",line->subs->tand);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Frequency</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"freq\" VALUE=\"%g\"\n",line->freq/line->units_freq->sf);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>\n");
fprintf(cgiOut,"<!-- frequency units menu -->\n");
fprintf(cgiOut,"%s\n",cgi_units_menu_display(menu_freq));
fprintf(cgiOut,"</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"SUBMIT\" NAME=\"analyze\" VALUE=\"Analyze\">\n");
fprintf(cgiOut,"<INPUT TYPE=\"SUBMIT\" NAME=\"reset\" VALUE=\"Reset\"></TD>\n");
fprintf(cgiOut,"<TD>Z0/k<INPUT TYPE=\"RADIO\" NAME=\"stype\" VALUE=\"zk\" %s\n",zkchecked);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>even/odd<INPUT TYPE=\"RADIO\" NAME=\"stype\" VALUE=\"evod\" %s\n",evodchecked);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Characteristic Impedance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"Ro\" VALUE=\"%g\"\n",line->z0);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[ohms]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Coupling Coefficient</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"k\" VALUE=\"%g\"\n",line->k);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[-]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Even Mode Impedance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"zeven\" VALUE=\"%g\"\n",line->z0e);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[ohms]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Odd Mode Impedance</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"zodd\" VALUE=\"%g\"\n",line->z0o);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[ohms]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"<!-- XXX -->\n");
fprintf(cgiOut,"<TR>\n");
fprintf(cgiOut,"<TD>Electrical Length</TD>\n");
fprintf(cgiOut,"<TD><INPUT TYPE=\"TEXT\" SIZE=10 NAME=\"elen\" VALUE=\"%g\"\n",line->len);
fprintf(cgiOut,"           onChange=\"valsChanged()\"></TD>\n");
fprintf(cgiOut,"<TD>[degrees]</TD>\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</TR>\n");
fprintf(cgiOut,"</TABLE>\n");
fprintf(cgiOut,"\n");
fprintf(cgiOut,"</FORM>\n");
fprintf(cgiOut,"\n");

/* *********        End of Generated Code           ******** */

